#
# Debug exports for semantic human anchors.
#

import argparse
import csv
import sys
from pathlib import Path

import numpy as np
import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from hugs.utils.anchor_io import (
    load_anchor_vertices,
    make_anchor_debug_dir,
    relative_to_cwd,
    save_anchor_binding_csv,
    save_anchor_binding_summary_csv,
    save_anchor_vertices,
    save_anchors_csv,
    save_anchors_pt,
)
from hugs.utils.anchor_utils import (
    bind_gaussians_to_anchors,
    build_initial_human_gaussians,
    compute_binding_local_mask,
    compute_anchor_local_features,
    compute_anchors,
    generate_semantic_anchor_vertices,
    load_smpl_template,
    make_template_from_vertices,
    summarize_anchor_quality,
)
from hugs.utils.anchor_visualization import (
    get_anchor_color,
    export_anchor_labels_legend,
    export_anchor_region_points,
    export_anchor_spheres_with_normals,
    export_binding_on_template_mesh,
    export_human_gaussian_anchor_points,
    export_human_gaussian_anchor_points_with_anchors,
    export_template_mesh_with_anchor_regions,
    export_template_mesh_with_anchor_spheres,
    export_template_mesh_with_anchor_spheres_normals,
    render_binding_pngs,
)
from hugs.utils.anchor_token import AnchorTokenPooler, attention_entropy, mean_pool_token


def write_readme(path, args, outputs, anchors):
    lines = [
        "# Exp A: Anchor Template Visualization",
        "",
        "This directory was generated by `scripts/debug_anchors.py --mode template`.",
        "",
        "## Inputs",
        "",
        f"- SMPL model path: `{args.smpl_model_path}`",
        f"- Anchor source: `{args.anchor_vertices if args.anchor_vertices else 'auto-generated heuristic anchors'}`",
        "",
        "## Outputs",
        "",
    ]
    for label, out_path in outputs:
        lines.append(f"- `{Path(out_path).name}`: {label}")
    lines.extend([
        "",
        "## Quick Checks",
        "",
        "- Open `template_mesh_anchor_regions.ply` to inspect colored anchor regions on the full SMPL mesh.",
        "- Open `template_anchors_with_normals.ply` to inspect anchor centers and outward normals.",
        "- Open `template_anchor_region_points.ply` if mesh vertex colors are hard to see in your viewer.",
        "- Use `anchors.csv` to inspect exact canonical positions, normals, radii, and vertex ids.",
        "",
        "## Anchor Summary",
        "",
    ])
    for row in summarize_anchor_quality(anchors):
        pos = ", ".join(f"{v:.4f}" for v in row["pos"])
        normal = ", ".join(f"{v:.4f}" for v in row["normal"])
        lines.append(
            f"- {row['name']}: n={row['num_vertices']}, "
            f"pos=[{pos}], normal=[{normal}], radius={row['radius']:.4f}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_template(args):
    out_dir = make_anchor_debug_dir(args.output_dir, "expA_template")
    template = load_smpl_template(args.smpl_model_path)

    if args.anchor_vertices:
        anchor_vertices = load_anchor_vertices(args.anchor_vertices)
    else:
        anchor_vertices = generate_semantic_anchor_vertices(
            template,
            count_per_anchor=args.count_per_anchor,
        )

    anchors = compute_anchors(template, anchor_vertices)

    anchor_vertices_path = out_dir / "anchor_vertices.json"
    anchors_pt_path = out_dir / "anchors.pt"
    anchors_csv_path = out_dir / "anchors.csv"
    mesh_path = out_dir / "template_mesh_anchor_regions.ply"
    mesh_spheres_path = out_dir / "template_mesh_anchor_spheres.ply"
    mesh_spheres_normals_path = out_dir / "template_mesh_anchor_spheres_normals.ply"
    points_path = out_dir / "template_anchor_region_points.ply"
    normals_path = out_dir / "template_anchors_with_normals.ply"
    legend_path = out_dir / "anchor_color_legend.ply"
    readme_path = out_dir / "README_expA.md"

    save_anchor_vertices(anchor_vertices, anchor_vertices_path)
    save_anchors_pt(anchors, anchors_pt_path)
    save_anchors_csv(anchors, anchors_csv_path)

    export_template_mesh_with_anchor_regions(
        mesh_path,
        template["vertices"],
        template["faces"],
        anchors,
    )
    export_template_mesh_with_anchor_spheres(
        mesh_spheres_path,
        template["vertices"],
        template["faces"],
        anchors,
        sphere_radius=args.mesh_sphere_radius,
    )
    export_template_mesh_with_anchor_spheres_normals(
        mesh_spheres_normals_path,
        template["vertices"],
        template["faces"],
        anchors,
        sphere_radius=args.mesh_sphere_radius,
        normal_length=args.normal_length,
        normal_radius=args.normal_radius,
    )
    export_anchor_region_points(points_path, template["vertices"], anchors)
    export_anchor_spheres_with_normals(
        normals_path,
        anchors,
        sphere_radius=args.sphere_radius,
        normal_length=args.normal_length,
    )
    export_anchor_labels_legend(legend_path, anchors)

    outputs = [
        ("fixed/generated anchor vertex indices", anchor_vertices_path),
        ("computed anchor tensors", anchors_pt_path),
        ("human-readable anchor table", anchors_csv_path),
        ("full SMPL mesh with colored anchor vertex regions", mesh_path),
        ("full SMPL mesh with colored solid anchor spheres", mesh_spheres_path),
        ("full SMPL mesh with anchor spheres plus normal arrows", mesh_spheres_normals_path),
        ("selected anchor vertices plus white center points", points_path),
        ("anchor center spheres plus white normal rays", normals_path),
        ("small color legend with anchor_id fields", legend_path),
        ("run notes and anchor summary", readme_path),
    ]
    write_readme(readme_path, args, outputs, anchors)

    print(f"Exp A outputs written to: {out_dir}")
    for label, out_path in outputs:
        print(f"- {relative_to_cwd(out_path)}  # {label}")

    if args.print_summary:
        print("\nAnchor summary:")
        for row in summarize_anchor_quality(anchors):
            pos = ", ".join(f"{v:.4f}" for v in row["pos"])
            normal = ", ".join(f"{v:.4f}" for v in row["normal"])
            print(
                f"{row['name']:>14s}: n={row['num_vertices']:3d}, "
                f"pos=[{pos}], normal=[{normal}], radius={row['radius']:.4f}"
            )


def write_bind_init_readme(path, args, outputs, anchors, bindings):
    counts = []
    top_ids = bindings["top1_anchor_id"]
    for idx, name in enumerate(anchors["names"]):
        counts.append((name, int((top_ids == idx).sum())))

    lines = [
        "# Exp B: Initial Human Gaussian -> Anchor Binding",
        "",
        "This directory was generated by `scripts/debug_anchors.py --mode bind_init`.",
        "",
        "The exported human Gaussians are the HUGS initial canonical Gaussians. In HUGS, these are initialized",
        "from SMPL template vertices in the vitruvian canonical pose, so the anchor centers are recomputed in",
        "that same canonical pose using the fixed `anchor_vertices.json` from Exp A.",
        "",
        "## Outputs",
        "",
    ]
    for label, out_path in outputs:
        lines.append(f"- `{Path(out_path).name}`: {label}")
    lines.extend([
        "",
        "## Recommended Files To Inspect",
        "",
        "- `human_gaussians_anchor_init_with_anchors.ply`: real human Gaussian points colored by top-1 anchor, plus anchor centers/normals.",
        "- `human_gaussians_anchor_init_local_with_anchors.ply`: same view, but far-away Gaussians are gray so anchor neighborhoods are easier to judge.",
        "- `human_gaussians_anchor_init_on_mesh.ply`: same binding shown on the SMPL canonical mesh.",
        "- `renders/*.png`: quick image snapshots from several views.",
        "",
        "## Top-1 Binding Counts",
        "",
    ])
    for name, count in counts:
        lines.append(f"- {name}: {count}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_binding_dict_from_inherited(anchor_ids, anchor_weights, anchors, mu):
    anchor_pos = anchors["pos_canon"].to(mu.device)
    top_ids = anchor_ids[:, 0]
    top_dist = torch.linalg.norm(mu - anchor_pos[top_ids], dim=1)
    sigma = torch.clamp(anchors["radius"].to(mu.device) * 1.8, min=0.035)
    return {
        "gaussian_anchor_ids": anchor_ids.cpu(),
        "gaussian_anchor_weights": anchor_weights.cpu(),
        "top1_anchor_id": top_ids.cpu(),
        "top1_anchor_dist": top_dist.cpu(),
        "sigma": sigma.cpu(),
    }


def write_anchor_stats_csv(path, iter_id, bindings, anchors, local_mask):
    path.parent.mkdir(parents=True, exist_ok=True)
    top_ids = bindings["top1_anchor_id"]
    top_dist = bindings["top1_anchor_dist"]
    top_weight = bindings["gaussian_anchor_weights"][:, 0]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "iter",
            "anchor_name",
            "num_gaussians",
            "num_local_gaussians",
            "mean_dist_to_anchor_canon",
            "max_dist_to_anchor_canon",
            "mean_assignment_weight",
        ])
        for anchor_id, name in enumerate(anchors["names"]):
            mask = top_ids == anchor_id
            local = mask & local_mask
            if mask.any():
                writer.writerow([
                    iter_id,
                    name,
                    int(mask.sum()),
                    int(local.sum()),
                    float(top_dist[mask].mean()),
                    float(top_dist[mask].max()),
                    float(top_weight[mask].mean()),
                ])
            else:
                writer.writerow([iter_id, name, 0, 0, "", "", ""])


def write_densify_demo_readme(path, outputs):
    lines = [
        "# Exp C: Densification Inheritance Visualization",
        "",
        "This is a non-invasive offline debug run. It simulates clone / split / prune on HUGS initial",
        "human Gaussians and explicitly inherits each child Gaussian's anchor ids/weights from its parent.",
        "",
        "Far-away Gaussians are gray in local visualizations, so anchor neighborhoods stay readable.",
        "",
        "## Outputs",
        "",
    ]
    for label, out_path in outputs:
        lines.append(f"- `{Path(out_path).name}`: {label}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_feature_stats_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def render_stats_heatmap(path, rows, metric_names):
    from PIL import Image, ImageDraw, ImageFont

    names = [r["anchor_name"] for r in rows]
    values = np.array([[float(r[m]) for m in metric_names] for r in rows], dtype=np.float32)
    finite = np.isfinite(values)
    norm = np.zeros_like(values, dtype=np.float32)
    for j in range(values.shape[1]):
        col = values[:, j]
        mask = finite[:, j]
        if mask.any():
            vmin, vmax = np.nanmin(col), np.nanmax(col)
            norm[:, j] = 0.5 if abs(vmax - vmin) < 1e-8 else (col - vmin) / (vmax - vmin)

    cell_w, cell_h = 86, 28
    left_w, top_h = 145, 120
    width = left_w + cell_w * len(metric_names)
    height = top_h + cell_h * len(names)
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()

    for j, metric in enumerate(metric_names):
        x = left_w + j * cell_w + 4
        draw.text((x, 8), metric.replace("_", "\n"), fill=(0, 0, 0), font=font)
    for i, name in enumerate(names):
        y = top_h + i * cell_h
        draw.text((8, y + 8), name, fill=(0, 0, 0), font=font)
        for j in range(len(metric_names)):
            t = float(norm[i, j])
            if not finite[i, j]:
                color = (230, 230, 230)
                text = "nan"
            else:
                color = (int(255 * t), int(170 * (1 - abs(t - 0.5) * 2)), int(255 * (1 - t)))
                text = f"{values[i, j]:.3g}"
            x = left_w + j * cell_w
            draw.rectangle((x, y, x + cell_w - 1, y + cell_h - 1), fill=color, outline=(255, 255, 255))
            draw.text((x + 4, y + 8), text, fill=(0, 0, 0), font=font)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def render_matrix_heatmap(path, matrix, row_names, col_names, title):
    from PIL import Image, ImageDraw, ImageFont

    matrix = np.asarray(matrix, dtype=np.float32)
    cell_w, cell_h = 34, 26
    left_w, top_h = 150, 70
    width = left_w + cell_w * len(col_names)
    height = top_h + cell_h * len(row_names)
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()
    draw.text((8, 8), title, fill=(0, 0, 0), font=font)
    vmin, vmax = np.nanmin(matrix), np.nanmax(matrix)
    denom = max(float(vmax - vmin), 1e-8)
    for j, name in enumerate(col_names):
        draw.text((left_w + j * cell_w + 2, 38), str(name)[:4], fill=(0, 0, 0), font=font)
    for i, name in enumerate(row_names):
        y = top_h + i * cell_h
        draw.text((8, y + 8), name, fill=(0, 0, 0), font=font)
        for j in range(len(col_names)):
            t = (matrix[i, j] - vmin) / denom
            color = (int(255 * t), int(80 + 120 * (1 - abs(t - 0.5) * 2)), int(255 * (1 - t)))
            x = left_w + j * cell_w
            draw.rectangle((x, y, x + cell_w - 1, y + cell_h - 1), fill=color, outline=(255, 255, 255))
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def render_token_scatter(path, tokens, names, title):
    from PIL import Image, ImageDraw, ImageFont

    x = np.asarray(tokens, dtype=np.float32)
    x = x - x.mean(axis=0, keepdims=True)
    _, _, vt = np.linalg.svd(x, full_matrices=False)
    pts = x @ vt[:2].T
    mins, maxs = pts.min(axis=0), pts.max(axis=0)
    pts = (pts - mins[None]) / np.maximum(maxs - mins, 1e-8)
    size = 900
    image = Image.new("RGB", (size, size), "white")
    draw = ImageDraw.Draw(image, "RGBA")
    font = ImageFont.load_default()
    draw.text((15, 12), title, fill=(0, 0, 0, 255), font=font)
    for idx, name in enumerate(names):
        px = 80 + pts[idx, 0] * (size - 160)
        py = 80 + (1.0 - pts[idx, 1]) * (size - 160)
        color = tuple(get_anchor_color(name, idx).tolist()) + (255,)
        draw.ellipse((px - 8, py - 8, px + 8, py + 8), fill=color, outline=(0, 0, 0, 255), width=2)
        draw.text((px + 10, py - 6), name, fill=(0, 0, 0, 235), font=font)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def write_feature_readme(path, outputs):
    lines = [
        "# Exp D: Anchor-local Gaussian Feature Statistics",
        "",
        "This run constructs deterministic per-Gaussian local features around each anchor and exports",
        "per-anchor statistics plus pooled feature vectors. No token network is trained in this stage.",
        "",
        "## Outputs",
        "",
    ]
    for label, out_path in outputs:
        lines.append(f"- `{Path(out_path).name}`: {label}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_feature_stats(args):
    out_dir = make_anchor_debug_dir(args.output_dir, "expD_feature_stats")
    anchor_vertices_path = args.anchor_vertices or "output/anchor_debug/expA_template/anchor_vertices.json"
    anchor_vertices = load_anchor_vertices(anchor_vertices_path)
    template = load_smpl_template(args.smpl_model_path, canonical_pose=args.binding_canonical_pose)
    anchors = compute_anchors(template, anchor_vertices)
    human = build_initial_human_gaussians(template)
    bindings = bind_gaussians_to_anchors(
        human["mu_canon"],
        human["lbs_weights"],
        anchors,
        top_m=args.top_m,
        lambda_lbs=args.lambda_lbs,
        sigma_scale=args.sigma_scale,
        min_sigma=args.min_sigma,
    )
    local_mask = compute_binding_local_mask(bindings, vis_radius_factor=args.vis_radius_factor)
    stats = compute_anchor_local_features(human, anchors, bindings, local_mask=local_mask)

    csv_path = out_dir / "anchor_feature_stats_init.csv"
    npy_path = out_dir / "anchor_feature_embeddings_init.npy"
    names_path = out_dir / "anchor_feature_embedding_names.txt"
    heatmap_path = out_dir / "anchor_feature_stats_heatmap_init.png"
    ply_path = out_dir / "anchor_feature_local_gaussians_init.ply"
    pt_path = out_dir / "anchor_local_features_init.pt"
    readme_path = out_dir / "README_expD.md"

    write_feature_stats_csv(csv_path, stats["stats_rows"])
    np.save(npy_path, stats["pooled_vectors"])
    names_path.write_text("\n".join(stats["pooled_names"]) + "\n", encoding="utf-8")
    torch.save(
        {
            "features_by_anchor": stats["features_by_anchor"],
            "feature_names": stats["feature_names"],
            "anchors": anchors,
            "bindings": bindings,
            "local_mask": local_mask,
        },
        pt_path,
    )
    export_human_gaussian_anchor_points_with_anchors(
        ply_path,
        human["mu_canon"].cpu().numpy(),
        bindings,
        anchors,
        sphere_radius=args.sphere_radius,
        normal_length=args.normal_length,
        local_mask=local_mask,
    )
    heatmap_metrics = [
        "num_local_gaussians",
        "mean_opacity",
        "mean_log_scale_x",
        "mean_extent_along_anchor_normal",
        "mean_distance_to_anchor",
        "weighted_mean_distance_to_anchor",
        "mean_lbs_entropy",
        "mean_assignment_weight",
    ]
    render_stats_heatmap(heatmap_path, stats["stats_rows"], heatmap_metrics)

    outputs = [
        ("per-anchor deterministic Gaussian feature statistics", csv_path),
        ("pooled per-anchor feature vectors for later PCA/t-SNE/token baselines", npy_path),
        ("row names for the pooled feature vector array", names_path),
        ("visual heatmap of key per-anchor statistics", heatmap_path),
        ("local Gaussian points used by the statistics, with anchors and normals", ply_path),
        ("raw per-anchor Gaussian feature tensors", pt_path),
        ("run notes", readme_path),
    ]
    write_feature_readme(readme_path, outputs)
    print(f"Exp D feature statistics written to: {out_dir}")
    for label, out_path in outputs:
        print(f"- {relative_to_cwd(out_path)}  # {label}")


def write_token_debug_csv(path, names, tokens, attn_stats):
    path.parent.mkdir(parents=True, exist_ok=True)
    norms = np.linalg.norm(tokens, axis=1)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["anchor_name", "token_norm", "num_features", "attention_entropy", "attention_max", "attention_min"])
        for idx, name in enumerate(names):
            st = attn_stats[idx]
            writer.writerow([
                name,
                float(norms[idx]),
                int(st["num_features"]),
                float(st["attention_entropy"]) if np.isfinite(st["attention_entropy"]) else "",
                float(st["attention_max"]) if np.isfinite(st["attention_max"]) else "",
                float(st["attention_min"]) if np.isfinite(st["attention_min"]) else "",
            ])


def write_token_readme(path, outputs):
    lines = [
        "# Exp D Part 2: Anchor Token Encoding Debug",
        "",
        "This run forwards deterministic anchor-local Gaussian features through an untrained token pooling",
        "network matching the manual's GaussianEncoder / AnchorQueryMLP / BiasMLP / attention pooling design.",
        "",
        "No loss is optimized here. The goal is interface validation, token shape checks, attention diagnostics,",
        "and visualizing whether different anchors produce distinguishable token vectors before training.",
        "",
        "## Outputs",
        "",
    ]
    for label, out_path in outputs:
        lines.append(f"- `{Path(out_path).name}`: {label}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_token_encode(args):
    out_dir = make_anchor_debug_dir(args.output_dir, "expD_token_encode")
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    anchor_vertices_path = args.anchor_vertices or "output/anchor_debug/expA_template/anchor_vertices.json"
    anchor_vertices = load_anchor_vertices(anchor_vertices_path)
    template = load_smpl_template(args.smpl_model_path, canonical_pose=args.binding_canonical_pose)
    anchors = compute_anchors(template, anchor_vertices)
    human = build_initial_human_gaussians(template)
    bindings = bind_gaussians_to_anchors(
        human["mu_canon"],
        human["lbs_weights"],
        anchors,
        top_m=args.top_m,
        lambda_lbs=args.lambda_lbs,
        sigma_scale=args.sigma_scale,
        min_sigma=args.min_sigma,
    )
    local_mask = compute_binding_local_mask(bindings, vis_radius_factor=args.vis_radius_factor)
    stats = compute_anchor_local_features(human, anchors, bindings, local_mask=local_mask)

    feature_names = stats["feature_names"]
    input_dim = len(feature_names)
    pooler = AnchorTokenPooler(input_dim=input_dim, num_anchors=len(anchors["names"]), hidden_dim=128)
    pooler.eval()

    mean_tokens = []
    attn_tokens = []
    attn_stats = []
    attention_weights = {}
    with torch.no_grad():
        for anchor_id, name in enumerate(anchors["names"]):
            feat = stats["features_by_anchor"][name].float()
            mean_tokens.append(mean_pool_token(feat, out_dim=128).cpu().numpy())
            if feat.numel() == 0:
                bias_feat = torch.empty((0, 4), dtype=torch.float32)
            else:
                # [distance, normal_distance, opacity, assignment_weight]
                bias_feat = torch.stack([feat[:, 3], feat[:, 4], feat[:, 11], feat[:, 13]], dim=1)
            token, alpha = pooler.forward_anchor(feat, bias_feat, anchor_id)
            attn_tokens.append(token.cpu().numpy())
            attention_weights[name] = alpha.cpu()
            if alpha.numel() == 0:
                attn_stats.append({
                    "num_features": 0,
                    "attention_entropy": float("nan"),
                    "attention_max": float("nan"),
                    "attention_min": float("nan"),
                })
            else:
                attn_stats.append({
                    "num_features": int(alpha.numel()),
                    "attention_entropy": float(attention_entropy(alpha)),
                    "attention_max": float(alpha.max()),
                    "attention_min": float(alpha.min()),
                })

    mean_tokens = np.stack(mean_tokens, axis=0).astype(np.float32)
    attn_tokens = np.stack(attn_tokens, axis=0).astype(np.float32)
    names = anchors["names"]

    mean_npy = out_dir / "anchor_tokens_mean_init.npy"
    attn_npy = out_dir / "anchor_tokens_attention_init.npy"
    names_txt = out_dir / "anchor_token_names.txt"
    csv_path = out_dir / "anchor_token_attention_stats_init.csv"
    attn_pt = out_dir / "anchor_attention_weights_init.pt"
    mean_scatter = out_dir / "anchor_tokens_mean_pca_init.png"
    attn_scatter = out_dir / "anchor_tokens_attention_pca_init.png"
    cosine_png = out_dir / "anchor_tokens_attention_cosine_init.png"
    readme_path = out_dir / "README_expD_token.md"

    np.save(mean_npy, mean_tokens)
    np.save(attn_npy, attn_tokens)
    names_txt.write_text("\n".join(names) + "\n", encoding="utf-8")
    write_token_debug_csv(csv_path, names, attn_tokens, attn_stats)
    torch.save({
        "attention_weights": attention_weights,
        "feature_names": feature_names,
        "anchor_names": names,
        "seed": args.seed,
        "note": "Untrained attention pooling debug forward.",
    }, attn_pt)

    render_token_scatter(mean_scatter, mean_tokens, names, "Mean-pooled anchor tokens PCA")
    render_token_scatter(attn_scatter, attn_tokens, names, "Untrained attention-pooled anchor tokens PCA")
    norm = attn_tokens / np.maximum(np.linalg.norm(attn_tokens, axis=1, keepdims=True), 1e-8)
    cosine = norm @ norm.T
    render_matrix_heatmap(cosine_png, cosine, names, names, "Attention token cosine similarity")

    outputs = [
        ("mean-pooled 128-d anchor tokens", mean_npy),
        ("untrained attention-pooled 128-d anchor tokens", attn_npy),
        ("anchor token row names", names_txt),
        ("attention entropy/max/min diagnostics", csv_path),
        ("raw attention weights per anchor", attn_pt),
        ("PCA visualization of deterministic mean tokens", mean_scatter),
        ("PCA visualization of untrained attention tokens", attn_scatter),
        ("cosine similarity heatmap of attention tokens", cosine_png),
        ("run notes", readme_path),
    ]
    write_token_readme(readme_path, outputs)
    print(f"Exp D token encoding outputs written to: {out_dir}")
    print(f"mean token shape: {mean_tokens.shape}")
    print(f"attention token shape: {attn_tokens.shape}")
    for label, out_path in outputs:
        print(f"- {relative_to_cwd(out_path)}  # {label}")


def simulate_inheritance_step(mu, anchor_ids, anchor_weights, anchors, rng, clone_frac, split_frac, prune_frac):
    bindings = make_binding_dict_from_inherited(anchor_ids, anchor_weights, anchors, mu)
    local_mask = compute_binding_local_mask(bindings, vis_radius_factor=1.35).to(mu.device)

    n_points = mu.shape[0]
    local_idx = torch.where(local_mask)[0]
    if local_idx.numel() == 0:
        local_idx = torch.arange(n_points, device=mu.device)

    clone_count = min(max(1, int(n_points * clone_frac)), local_idx.numel())
    clone_parent = local_idx[torch.as_tensor(rng.permutation(local_idx.numel())[:clone_count], device=mu.device)]
    clone_noise = torch.from_numpy(rng.normal(0.0, 0.006, size=(clone_count, 3))).to(mu.device).float()
    clone_mu = mu[clone_parent] + clone_noise
    clone_ids = anchor_ids[clone_parent].clone()
    clone_weights = anchor_weights[clone_parent].clone()

    split_count = min(max(1, int(n_points * split_frac)), local_idx.numel())
    split_parent = local_idx[torch.as_tensor(rng.permutation(local_idx.numel())[:split_count], device=mu.device)]
    split_children = 2
    split_noise = torch.from_numpy(rng.normal(0.0, 0.014, size=(split_count * split_children, 3))).to(mu.device).float()
    split_mu = mu[split_parent].repeat(split_children, 1) + split_noise
    split_ids = anchor_ids[split_parent].repeat(split_children, 1).clone()
    split_weights = anchor_weights[split_parent].repeat(split_children, 1).clone()

    keep = torch.ones(n_points, dtype=torch.bool, device=mu.device)
    keep[split_parent] = False
    prune_candidates = torch.where((~local_mask) & keep)[0]
    prune_count = min(int(n_points * prune_frac), prune_candidates.numel())
    if prune_count > 0:
        prune_idx = prune_candidates[
            torch.as_tensor(rng.permutation(prune_candidates.numel())[:prune_count], device=mu.device)
        ]
        keep[prune_idx] = False

    next_mu = torch.cat([mu[keep], clone_mu, split_mu], dim=0)
    next_ids = torch.cat([anchor_ids[keep], clone_ids, split_ids], dim=0)
    next_weights = torch.cat([anchor_weights[keep], clone_weights, split_weights], dim=0)
    return next_mu, next_ids, next_weights


def run_densify_demo(args):
    out_dir = make_anchor_debug_dir(args.output_dir, "expC_densify_inherit")
    anchor_vertices_path = args.anchor_vertices or "output/anchor_debug/expA_template/anchor_vertices.json"
    anchor_vertices = load_anchor_vertices(anchor_vertices_path)
    template = load_smpl_template(args.smpl_model_path, canonical_pose=args.binding_canonical_pose)
    anchors = compute_anchors(template, anchor_vertices)
    human = build_initial_human_gaussians(template)

    init_bindings = bind_gaussians_to_anchors(
        human["mu_canon"],
        human["lbs_weights"],
        anchors,
        top_m=args.top_m,
        lambda_lbs=args.lambda_lbs,
        sigma_scale=args.sigma_scale,
        min_sigma=args.min_sigma,
    )
    mu = human["mu_canon"].clone()
    anchor_ids = init_bindings["gaussian_anchor_ids"].clone()
    anchor_weights = init_bindings["gaussian_anchor_weights"].clone()
    rng = np.random.default_rng(args.seed)
    iter_specs = [
        (0, 0.00, 0.00, 0.00),
        (3000, 0.10, 0.04, 0.02),
        (6000, 0.08, 0.04, 0.02),
        (12000, 0.05, 0.03, 0.015),
    ]
    outputs = []

    for iter_id, clone_frac, split_frac, prune_frac in iter_specs:
        if iter_id > 0:
            mu, anchor_ids, anchor_weights = simulate_inheritance_step(
                mu,
                anchor_ids,
                anchor_weights,
                anchors,
                rng,
                clone_frac=clone_frac,
                split_frac=split_frac,
                prune_frac=prune_frac,
            )

        bindings = make_binding_dict_from_inherited(anchor_ids, anchor_weights, anchors, mu)
        local_mask = compute_binding_local_mask(bindings, vis_radius_factor=args.vis_radius_factor)
        torch.save(
            {
                **bindings,
                "local_mask": local_mask,
                "anchor_names": anchors["names"],
                "mu_canon": mu.cpu(),
                "iter": iter_id,
            },
            out_dir / f"anchor_bindings_iter{iter_id:04d}.pt",
        )

        ply_path = out_dir / f"human_gaussians_anchor_iter{iter_id:04d}.ply"
        local_ply_path = out_dir / f"human_gaussians_anchor_iter{iter_id:04d}_local_with_anchors.ply"
        stats_path = out_dir / f"anchor_stats_iter{iter_id:04d}.csv"
        export_human_gaussian_anchor_points(ply_path, mu.cpu().numpy(), bindings, anchors)
        export_human_gaussian_anchor_points_with_anchors(
            local_ply_path,
            mu.cpu().numpy(),
            bindings,
            anchors,
            sphere_radius=args.sphere_radius,
            normal_length=args.normal_length,
            local_mask=local_mask,
        )
        write_anchor_stats_csv(stats_path, iter_id, bindings, anchors, local_mask)
        outputs.extend([
            (f"all inherited bindings at iter {iter_id}", ply_path),
            (f"local inherited bindings plus anchors at iter {iter_id}", local_ply_path),
            (f"anchor count/distance stats at iter {iter_id}", stats_path),
        ])

        if args.render_images:
            pngs = render_binding_pngs(
                out_dir / "renders",
                mu.cpu().numpy(),
                bindings,
                anchors,
                image_size=args.image_size,
                local_mask=local_mask,
                suffix=f"_iter{iter_id:04d}_local",
            )
            outputs.extend((f"local PNG snapshot at iter {iter_id}", p) for p in pngs)

    readme_path = out_dir / "README_expC.md"
    write_densify_demo_readme(readme_path, outputs)
    outputs.append(("run notes", readme_path))
    print(f"Exp C outputs written to: {out_dir}")
    for label, out_path in outputs:
        print(f"- {relative_to_cwd(out_path)}  # {label}")


def project_points_to_image(points, camera):
    pts = torch.as_tensor(points, dtype=torch.float32, device=camera["world_view_transform"].device)
    ones = torch.ones((pts.shape[0], 1), dtype=pts.dtype, device=pts.device)
    pts_h = torch.cat([pts, ones], dim=1)
    clip = pts_h @ camera["full_proj_transform"]
    ndc = clip[:, :3] / clip[:, 3:4].clamp(min=1e-6)
    width = float(camera["image_width"])
    height = float(camera["image_height"])
    x = (ndc[:, 0] + 1.0) * 0.5 * width
    y = (ndc[:, 1] + 1.0) * 0.5 * height
    return torch.stack([x, y, ndc[:, 2]], dim=1)


def draw_overlay_on_render(image_tensor, camera, anchors, bindings, mu_canon, out_path, local_mask=None):
    from PIL import Image, ImageDraw, ImageFont

    image = (image_tensor.detach().cpu().permute(1, 2, 0).numpy().clip(0, 1) * 255).astype(np.uint8)
    pil = Image.fromarray(image)
    draw = ImageDraw.Draw(pil, "RGBA")
    font = ImageFont.load_default()

    mu_2d = project_points_to_image(mu_canon, camera).detach().cpu().numpy()
    anchor_2d = project_points_to_image(anchors["pos_canon"], camera).detach().cpu().numpy()
    normal_end = anchors["pos_canon"] + anchors["normal_canon"] * 0.12
    normal_2d = project_points_to_image(normal_end, camera).detach().cpu().numpy()

    top_ids = bindings["top1_anchor_id"].detach().cpu().numpy()
    if local_mask is None:
        local_mask_np = np.ones(top_ids.shape[0], dtype=bool)
    else:
        local_mask_np = local_mask.detach().cpu().numpy().astype(bool)

    height, width = image.shape[:2]
    for anchor_id, name in enumerate(anchors["names"]):
        color = tuple(get_anchor_color(name, anchor_id).tolist())
        mask = (top_ids == anchor_id) & local_mask_np
        pts = mu_2d[mask]
        pts = pts[(pts[:, 0] >= 0) & (pts[:, 0] < width) & (pts[:, 1] >= 0) & (pts[:, 1] < height)]
        for x, y, _ in pts[:: max(1, len(pts) // 350)]:
            draw.ellipse((x - 1.5, y - 1.5, x + 1.5, y + 1.5), fill=color + (185,))

        ax, ay, _ = anchor_2d[anchor_id]
        nx, ny, _ = normal_2d[anchor_id]
        if 0 <= ax < width and 0 <= ay < height:
            r = 7
            draw.ellipse((ax - r, ay - r, ax + r, ay + r), fill=color + (255,), outline=(0, 0, 0, 255), width=2)
            draw.line((ax, ay, nx, ny), fill=(0, 0, 0, 255), width=2)
            draw.ellipse((nx - 3, ny - 3, nx + 3, ny + 3), fill=(255, 214, 64, 255))
            draw.text((ax + r + 3, ay - r), name, fill=(0, 0, 0, 245), font=font)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    pil.save(out_path)


def run_raster_overlay(args):
    from hugs.datasets.utils import get_rotating_camera
    from hugs.renderer.gs_renderer import render
    from hugs.utils.rotations import matrix_to_quaternion, rotation_6d_to_matrix
    from hugs.models.hugs_trimlp import HUGS_TRIMLP

    out_dir = make_anchor_debug_dir(args.output_dir, "expC_raster_overlay")
    anchor_vertices_path = args.anchor_vertices or "output/anchor_debug/expA_template/anchor_vertices.json"
    anchor_vertices = load_anchor_vertices(anchor_vertices_path)

    device = "cuda"
    model = HUGS_TRIMLP(sh_degree=3, n_subdivision=args.n_subdivision, betas=torch.zeros(10, device=device))
    init_vals = model.initialize()
    mu = model.get_xyz.detach()
    template = make_template_from_vertices(
        model.get_vitruvian_verts_template(),
        model.smpl_template.faces,
        model.smpl_template.lbs_weights,
        canonical_pose="hugs_vitruvian",
    )
    anchors = compute_anchors(template, anchor_vertices)
    bindings = bind_gaussians_to_anchors(
        mu.detach().cpu(),
        init_vals["lbs_weights"].detach().cpu(),
        anchors,
        top_m=args.top_m,
        lambda_lbs=args.lambda_lbs,
        sigma_scale=args.sigma_scale,
        min_sigma=args.min_sigma,
    )
    local_mask = compute_binding_local_mask(bindings, vis_radius_factor=args.vis_radius_factor)
    scales = init_vals["scales"].detach()
    rotq = matrix_to_quaternion(rotation_6d_to_matrix(init_vals["rot6d_canon"].detach()))
    opacity = init_vals["opacity"].detach().clamp(min=0.18)

    top_ids = bindings["top1_anchor_id"].to(device)
    local_mask_dev = local_mask.to(device)
    rgb = torch.full((mu.shape[0], 3), 0.72, dtype=torch.float32, device=device)
    for idx, name in enumerate(anchors["names"]):
        color = torch.tensor(get_anchor_color(name, idx), dtype=torch.float32, device=device) / 255.0
        rgb[(top_ids == idx) & local_mask_dev] = color

    cameras = get_rotating_camera(img_size=args.image_size, fov=0.4, dist=5.0, device=device, nframes=args.overlay_frames)
    bg = torch.ones(3, dtype=torch.float32, device=device)
    outputs = []
    for frame_id, cam in enumerate(cameras):
        pkg = render(
            means3D=mu,
            feats=rgb,
            opacity=opacity,
            scales=scales,
            rotations=rotq,
            data=cam,
            scaling_modifier=1.0,
            bg_color=bg,
            active_sh_degree=0,
        )
        raw_path = out_dir / f"raster_anchor_binding_frame{frame_id:03d}.png"
        overlay_path = out_dir / f"raster_anchor_binding_frame{frame_id:03d}_overlay.png"
        from PIL import Image
        raw = (pkg["render"].detach().cpu().permute(1, 2, 0).numpy().clip(0, 1) * 255).astype(np.uint8)
        Image.fromarray(raw).save(raw_path)
        draw_overlay_on_render(pkg["render"], cam, anchors, bindings, mu.detach().cpu(), overlay_path, local_mask=local_mask)
        outputs.extend([raw_path, overlay_path])

    print(f"Raster overlay outputs written to: {out_dir}")
    for path in outputs:
        print(f"- {relative_to_cwd(path)}")


def run_bind_init(args):
    out_dir = make_anchor_debug_dir(args.output_dir, "expB_bind_init")
    anchor_vertices_path = args.anchor_vertices or "output/anchor_debug/expA_template/anchor_vertices.json"
    anchor_vertices = load_anchor_vertices(anchor_vertices_path)

    template = load_smpl_template(args.smpl_model_path, canonical_pose=args.binding_canonical_pose)
    anchors = compute_anchors(template, anchor_vertices)
    human = build_initial_human_gaussians(template)
    bindings = bind_gaussians_to_anchors(
        human["mu_canon"],
        human["lbs_weights"],
        anchors,
        top_m=args.top_m,
        lambda_lbs=args.lambda_lbs,
        sigma_scale=args.sigma_scale,
        min_sigma=args.min_sigma,
    )
    local_mask = compute_binding_local_mask(bindings, vis_radius_factor=args.vis_radius_factor)

    binding_pt = out_dir / "anchor_bindings_init.pt"
    binding_csv = out_dir / "human_gaussians_anchor_init.csv"
    summary_csv = out_dir / "anchor_binding_summary_init.csv"
    anchors_pt = out_dir / "anchors_hugs_canonical.pt"
    anchors_csv = out_dir / "anchors_hugs_canonical.csv"
    points_ply = out_dir / "human_gaussians_anchor_init.ply"
    points_with_anchors_ply = out_dir / "human_gaussians_anchor_init_with_anchors.ply"
    local_points_ply = out_dir / "human_gaussians_anchor_init_local.ply"
    local_points_with_anchors_ply = out_dir / "human_gaussians_anchor_init_local_with_anchors.ply"
    mesh_ply = out_dir / "human_gaussians_anchor_init_on_mesh.ply"
    local_mesh_ply = out_dir / "human_gaussians_anchor_init_local_on_mesh.ply"
    readme_path = out_dir / "README_expB.md"
    render_dir = out_dir / "renders"

    torch.save(
        {
            **bindings,
            "anchor_names": anchors["names"],
            "mu_canon": human["mu_canon"].cpu(),
            "gaussian_lbs": human["lbs_weights"].cpu(),
            "canonical_pose": args.binding_canonical_pose,
            "anchor_vertices_path": str(anchor_vertices_path),
            "score": {
                "top_m": args.top_m,
                "lambda_lbs": args.lambda_lbs,
                "sigma_scale": args.sigma_scale,
                "min_sigma": args.min_sigma,
                "vis_radius_factor": args.vis_radius_factor,
            },
            "local_mask": local_mask.cpu(),
        },
        binding_pt,
    )
    save_anchors_pt(anchors, anchors_pt)
    save_anchors_csv(anchors, anchors_csv)
    save_anchor_binding_csv(bindings, anchors, binding_csv)
    save_anchor_binding_summary_csv(bindings, anchors, summary_csv)

    mu_np = human["mu_canon"].cpu().numpy()
    export_human_gaussian_anchor_points(points_ply, mu_np, bindings, anchors)
    export_human_gaussian_anchor_points_with_anchors(
        points_with_anchors_ply,
        mu_np,
        bindings,
        anchors,
        sphere_radius=args.sphere_radius,
        normal_length=args.normal_length,
    )
    export_human_gaussian_anchor_points(local_points_ply, mu_np, bindings, anchors, local_mask=local_mask)
    export_human_gaussian_anchor_points_with_anchors(
        local_points_with_anchors_ply,
        mu_np,
        bindings,
        anchors,
        sphere_radius=args.sphere_radius,
        normal_length=args.normal_length,
        local_mask=local_mask,
    )
    export_binding_on_template_mesh(mesh_ply, template["vertices"], template["faces"], bindings, anchors)
    export_binding_on_template_mesh(local_mesh_ply, template["vertices"], template["faces"], bindings, anchors, local_mask=local_mask)

    png_paths = []
    if args.render_images:
        png_paths = render_binding_pngs(render_dir, mu_np, bindings, anchors, image_size=args.image_size)
        png_paths.extend(
            render_binding_pngs(
                render_dir,
                mu_np,
                bindings,
                anchors,
                image_size=args.image_size,
                local_mask=local_mask,
                suffix="_local",
            )
        )

    outputs = [
        ("binding tensors, top-m anchor ids/weights, and score metadata", binding_pt),
        ("per-Gaussian binding table", binding_csv),
        ("per-anchor top-1 Gaussian counts and distance statistics", summary_csv),
        ("anchors recomputed in HUGS canonical pose", anchors_pt),
        ("human-readable anchors in HUGS canonical pose", anchors_csv),
        ("human Gaussian point cloud colored by top-1 anchor", points_ply),
        ("human Gaussian point cloud plus anchor centers and normal rays", points_with_anchors_ply),
        ("local-only point cloud; far-away Gaussians are gray", local_points_ply),
        ("local-only point cloud plus anchor centers and normal rays", local_points_with_anchors_ply),
        ("same binding visualized as colors on canonical SMPL mesh", mesh_ply),
        ("local-only binding visualized on canonical SMPL mesh", local_mesh_ply),
        ("run notes and binding count summary", readme_path),
    ]
    for png in png_paths:
        outputs.append(("PNG snapshot of colored human Gaussian binding", png))
    write_bind_init_readme(readme_path, args, outputs, anchors, bindings)

    print(f"Exp B outputs written to: {out_dir}")
    for label, out_path in outputs:
        print(f"- {relative_to_cwd(out_path)}  # {label}")

    if args.print_summary:
        print("\nTop-1 binding counts:")
        top_ids = bindings["top1_anchor_id"]
        for idx, name in enumerate(anchors["names"]):
            mask = top_ids == idx
            local = mask & local_mask
            if mask.any():
                dist = bindings["top1_anchor_dist"][mask]
                weight = bindings["gaussian_anchor_weights"][mask, 0]
                print(
                    f"{name:>14s}: n={int(mask.sum()):4d}, "
                    f"local={int(local.sum()):4d}, "
                    f"mean_dist={float(dist.mean()):.4f}, max_dist={float(dist.max()):.4f}, "
                    f"mean_weight={float(weight.mean()):.4f}"
                )
            else:
                print(f"{name:>14s}: n=0")


def parse_args():
    parser = argparse.ArgumentParser(description="Anchor debug exports for HUGS.")
    parser.add_argument(
        "--mode",
        default="template",
        choices=["template", "bind_init", "densify_demo", "feature_stats", "token_encode", "raster_overlay"],
        help="Debug export mode. Exp C rasterized overlays use raster_overlay.",
    )
    parser.add_argument(
        "--smpl-model-path",
        default="data/smpl",
        help="Path to SMPL_NEUTRAL.pkl or a directory containing it.",
    )
    parser.add_argument(
        "--anchor-vertices",
        default=None,
        help="Optional existing anchor_vertices.json. Exp B defaults to output/anchor_debug/expA_template/anchor_vertices.json.",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Output root. Results are written under <output-dir>/anchor_debug/expA_template.",
    )
    parser.add_argument(
        "--count-per-anchor",
        type=int,
        default=64,
        help="Number of SMPL vertices selected per auto-generated anchor.",
    )
    parser.add_argument(
        "--sphere-radius",
        type=float,
        default=0.018,
        help="Point-sphere radius for anchor center visualization.",
    )
    parser.add_argument(
        "--mesh-sphere-radius",
        type=float,
        default=0.026,
        help="Solid sphere radius for the combined template mesh visualization.",
    )
    parser.add_argument(
        "--normal-length",
        type=float,
        default=0.11,
        help="Normal ray length for anchor center visualization.",
    )
    parser.add_argument(
        "--normal-radius",
        type=float,
        default=0.004,
        help="Solid normal arrow shaft radius for the combined mesh visualization.",
    )
    parser.add_argument(
        "--binding-canonical-pose",
        default="hugs_vitruvian",
        choices=["hugs_vitruvian", "vitruvian", "t_pose", "template"],
        help="Canonical pose used for Exp B human Gaussian binding.",
    )
    parser.add_argument("--top-m", type=int, default=2, help="Number of sparse soft anchor assignments per Gaussian.")
    parser.add_argument("--lambda-lbs", type=float, default=0.35, help="LBS distance weight in the binding score.")
    parser.add_argument("--sigma-scale", type=float, default=1.8, help="Multiplier for per-anchor region radius in distance score.")
    parser.add_argument("--min-sigma", type=float, default=0.035, help="Minimum anchor sigma in meters for binding.")
    parser.add_argument("--render-images", action="store_true", help="Save PNG snapshots of the Exp B binding visualization.")
    parser.add_argument("--image-size", type=int, default=1500, help="PNG snapshot size in pixels.")
    parser.add_argument("--overlay-frames", type=int, default=4, help="Number of rasterized camera views for anchor overlay.")
    parser.add_argument("--n-subdivision", type=int, default=2, help="HUGS SMPL subdivision level for raster overlay.")
    parser.add_argument("--seed", type=int, default=12345, help="Random seed for Exp C offline densification demo.")
    parser.add_argument(
        "--vis-radius-factor",
        type=float,
        default=1.35,
        help="For local-only visualization, color points only if distance <= sigma * this factor.",
    )
    parser.add_argument(
        "--print-summary",
        action="store_true",
        help="Print anchor positions/normals after export.",
    )
    return parser.parse_args()


def main():
    torch.set_grad_enabled(False)
    args = parse_args()
    if args.mode == "template":
        run_template(args)
    elif args.mode == "bind_init":
        run_bind_init(args)
    elif args.mode == "densify_demo":
        run_densify_demo(args)
    elif args.mode == "feature_stats":
        run_feature_stats(args)
    elif args.mode == "token_encode":
        run_token_encode(args)
    elif args.mode == "raster_overlay":
        run_raster_overlay(args)
    else:
        raise ValueError(f"Unsupported mode: {args.mode}")


if __name__ == "__main__":
    main()
